version: '3.8'

# Production configuration with resource limits and security options

services:
  stream-plus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    
    image: stream-plus:latest
    container_name: stream-plus
    restart: always
    
    environment:
      - FLASK_DEBUG=false
      - PORT=${PORT:-5000}
      - TZ=${TZ:-UTC}
      - DISPATCHARR_API_URL=http://127.0.0.1:9191
      - DISPATCHARR_API_USER=user
      - DISPATCHARR_API_PASSWORD=password

    ports:
      - "${HOST_PORT:-5000}:5000"
    
    volumes:
      - ./rules:/app/rules
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
