version: '3.8'

services:
  stream-plus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
    
    container_name: stream-plus
    restart: unless-stopped
    
    environment:
      # Dispatcharr API configuration (required)
      - DISPATCHARR_API_URL=http://dispatcharr:8080
      - DISPATCHARR_API_USER=admin
      - DISPATCHARR_API_PASSWORD=changeme
      
      # Flask configuration (optional)
      - PORT=5000
      - FLASK_DEBUG=false
      - SECRET_KEY=change-this-secret-key-in-production
      
      # Timezone (optional)
      - TZ=Europe/Madrid
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./rules:/app/rules
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - stream-plus-network

networks:
  stream-plus-network:
    driver: bridge
