version: '3.8'

# Production configuration with resource limits and security options

services:
  stream-plus:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    
    image: stream-plus:latest
    container_name: stream-plus
    restart: always
    
    env_file:
      - .env
    
    environment:
      - FLASK_DEBUG=false
      - PORT=${PORT:-5000}
      - TZ=${TZ:-UTC}
    
    ports:
      - "${HOST_PORT:-5000}:5000"
    
    volumes:
      - ./rules:/app/rules
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    
    networks:
      - stream-plus-network
    
    security_opt:
      - no-new-privileges:true

networks:
  stream-plus-network:
    driver: bridge
