services:
  stream-plus:
    image: bernouilli/stream-plus:latest
    container_name: stream-plus
    restart: unless-stopped
    
    environment:
      # Dispatcharr API configuration (required)
      - DISPATCHARR_API_URL=http://127.0.0.1:9191
      - DISPATCHARR_API_USER=user
      - DISPATCHARR_API_PASSWORD=password
      # Flask configuration (optional)
      - PORT=5000
      - FLASK_DEBUG=false
      - SECRET_KEY=change-this-secret-key-in-production
      
      # Stream testing configuration (optional)
      - STREAM_TEST_DURATION=10
      - STREAM_TEST_TIMEOUT_BUFFER=30
      - STREAM_TEST_DELAY=3
      
      # Timezone (optional)
      - TZ=Europe/Madrid
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./rules:/app/rules
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
