# Production configuration with resource limits and security options

services:
  stream-plus:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: stream-plus:latest
    container_name: stream-plus
    restart: always
    
    environment:
      - FLASK_DEBUG=false
      - PORT=${PORT:-5000}
      - TZ=${TZ:-UTC}
      - DISPATCHARR_API_URL=http://host.docker.internal:9191
      - DISPATCHARR_API_USER=user
      - DISPATCHARR_API_PASSWORD=password
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - STREAM_TEST_DURATION=${STREAM_TEST_DURATION:-10}
      - STREAM_TEST_TIMEOUT_BUFFER=${STREAM_TEST_TIMEOUT_BUFFER:-30}
      - STREAM_TEST_DELAY=${STREAM_TEST_DELAY:-3}
      - STREAM_TEST_USER_AGENT=${STREAM_TEST_USER_AGENT:-Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.3}

    ports:
      - "${HOST_PORT:-5000}:5000"
    
    volumes:
      - ./rules:/app/rules
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
