services:
  stream-plus:
    image: bernouilli/stream-plus:latest
    container_name: stream-plus
    restart: unless-stopped
    
    environment:
      # Dispatcharr API configuration (required)
      - DISPATCHARR_API_URL=http://host.docker.internal:9191
      - DISPATCHARR_API_USER=user
      - DISPATCHARR_API_PASSWORD=password
      # Flask configuration (optional)
      - PORT=5000
      - FLASK_DEBUG=false
      - SECRET_KEY=change-this-secret-key-in-production

      # User configuration (optional)
      - USER_UID=1000
      - USER_GID=1000
      
      # Stream testing configuration (optional)
      - STREAM_TEST_DURATION=10
      - STREAM_TEST_TIMEOUT_BUFFER=30
      - STREAM_TEST_DELAY=3
      - STREAM_TEST_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.3
      
      # Timezone (optional) - Use timezone names like 'Europe/Madrid' or offset like 'UTC+2'
      - TZ=UTC+2
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./rules:/app/rules
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
