services:
  stream-plus:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: stream-plus-dev
    restart: unless-stopped

    environment:
      # Dispatcharr API configuration (required)
      - DISPATCHARR_API_URL=http://127.0.0.1:9191
      - DISPATCHARR_API_USER=user
      - DISPATCHARR_API_PASSWORD=password
      # Flask configuration (optional)
      - PORT=5000
      - FLASK_DEBUG=true
      - SECRET_KEY=change-this-secret-key-in-production

      # User configuration (optional)
      - USER_UID=1000
      - USER_GID=1000

      # Stream testing configuration (optional)
      - STREAM_TEST_DURATION=10
      - STREAM_TEST_TIMEOUT_BUFFER=30

      # Timezone (optional)
      - TZ=Europe/Madrid

    ports:
      - "5000:5000"

    volumes:
      - ./rules:/app/rules
      # Mount source code for development (optional)
      - .:/app

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s